<a href="https://colab.research.google.com/github/lisagamilton/python_for_data_analysis/blob/main/database_connection_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd

In [20]:
credentials = service_account.Credentials.from_service_account_file('/content/credentials.json')

In [21]:
project_id = 'my-project-26-01-2026'
client = bigquery.Client(credentials = credentials, project=project_id)
query_text = f"""SELECT * FROM `my-project-26-01-2026.dataset1.customers_data`
LIMIT 100;"""
query = client.query(query_text)

In [22]:
customers_data = query.to_dataframe()
customers_data

   customer_id gender   age
0      C126436   Male  '18'
1      C166635   Male  '18'
2      C322924   Male  '18'
3      C129846   Male  '18'
4      C195508   Male  '18'
..         ...    ...   ...
95     C335970   Male  '18'
96     C852186   Male  '18'
97     C339505   Male  '18'
98     C516713   Male  '18'
99     C458349   Male  '18'

[100 rows x 3 columns]

In [23]:
customers_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  100 non-null    object
 1   gender       100 non-null    object
 2   age          100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

In [24]:
query_text1 = f"""SELECT * FROM `my-project-26-01-2026.dataset1.shopping_data`;"""
query1 = client.query(query_text1)

In [25]:
shopping_data = query1.to_dataframe()
shopping_data

,invoice_no,customer_id,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I318200,C203784,Technology,1,1050,Debit Card,2021-11-24,Kanyon
1,I135869,C330583,Technology,1,1050,Credit Card,2022-02-20,Kanyon
2,I286572,C334905,Technology,1,1050,Cash,2021-08-20,Kanyon
3,I753933,C378941,Technology,1,1050,Credit Card,2022-09-19,Kanyon
4,I107806,C234672,Technology,1,1050,Cash,2022-02-18,Kanyon
...,...,...,...,...,...,...,...,...
196506,I370941,C277502,Shoes,5,"3000,85",Cash,2022-05-20,Emaar Square Mall
196507,I631073,C132270,Shoes,5,"3000,85",Debit Card,2021-04-10,Emaar Square Mall
196508,I261172,C237656,Shoes,5,"3000,85",Cash,2022-09-04,Emaar Square Mall
196509,I107352,C821850,Shoes,5,"3000,85",Cash,2021-12-09,Emaar Square Mall
196510,I285543,C175871,Shoes,5,"3000,85",Cash,2021-01-15,Emaar Square Mall

In [26]:
shopping_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196511 entries, 0 to 196510
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   invoice_no      196511 non-null  object
 1   customer_id     196511 non-null  object
 2   category        193928 non-null  object
 3   quantity        196511 non-null  object
 4   price           196511 non-null  object
 5   payment_method  196511 non-null  object
 6   invoice_date    196511 non-null  object
 7   shopping_mall   196479 non-null  object
dtypes: object(8)
memory usage: 12.0+ MB

In [27]:
shopping_data.describe()

,invoice_no,customer_id,category,quantity,price,payment_method,invoice_date,shopping_mall
count,196511,196511,193928,196511,196511,196511,196511,196479
unique,99457,99457,8,5,40,3,797,10
top,I286572,C334905,Clothing,3,"600,16",Cash,2021-11-24,Mall of Istanbul
freq,3,3,67231,39785,13730,87851,317,39886

In [29]:
united_data = pd.merge(customers_data, shopping_data,how='left',on='customer_id')
united_data

,customer_id,gender,age,invoice_no,category,quantity,price,payment_method,invoice_date,shopping_mall
0,C126436,Male,'18',I269690,Cosmetics,3,"121,98",Debit Card,2022-02-07,Zorlu Center
1,C126436,Male,'18',I269690,None,3,"121,98",Debit Card,2022-02-07,Zorlu Center
2,C166635,Male,'18',I293215,Cosmetics,4,"162,64",Credit Card,2021-12-12,Istinye Park
3,C166635,Male,'18',I293215,Cosmetics,4,"162,64",Credit Card,2021-12-12,Istinye Park
4,C322924,Male,'18',I135098,Clothing,5,"1500,4",Cash,2022-09-09,Kanyon
...,...,...,...,...,...,...,...,...,...,...
191,C339505,Male,'18',I278203,Technology,4,4200,Debit Card,2021-10-29,Mall of Istanbul
192,C516713,Male,'18',I187498,Cosmetics,5,"203,3",Debit Card,2021-08-07,Istinye Park
193,C516713,Male,'18',I187498,Cosmetics,5,"203,3",Debit Card,2021-08-07,Istinye Park
194,C458349,Male,'18',I482801,Toys,3,"107,52",Credit Card,2022-01-25,Mall of Istanbul
195,C458349,Male,'18',I482801,Toys,3,"107,52",Credit Card,2022-01-25,Mall of Istanbul

In [30]:
united_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     196 non-null    object
 1   gender          196 non-null    object
 2   age             196 non-null    object
 3   invoice_no      196 non-null    object
 4   category        194 non-null    object
 5   quantity        196 non-null    object
 6   price           196 non-null    object
 7   payment_method  196 non-null    object
 8   invoice_date    196 non-null    object
 9   shopping_mall   196 non-null    object
dtypes: object(10)
memory usage: 15.4+ KB

In [36]:
united_data['price'] = united_data['price'].replace(',','.',regex=True).astype('float')
united_data['category'] = united_data['category'].fillna('UNKNOWN')
united_data['invoice_date'] = pd.to_datetime(united_data['invoice_date'])
united_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     196 non-null    object
 1   gender          196 non-null    object
 2   age             196 non-null    object
 3   invoice_no      196 non-null    object
 4   category        196 non-null    object
 5   quantity        196 non-null    object
 6   price           196 non-null    float64
 7   payment_method  196 non-null    object
 8   invoice_date    196 non-null    datetime64[ns]
 9   shopping_mall   196 non-null    object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 15.4+ KB

In [37]:
united_data.to_gbq(
    destination_table="dataset1.united_data",
    project_id="my-project-26-01-2026",
    credentials=credentials
)

/tmp/ipykernel_7263/640800290.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  united_data.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 11214.72it/s]