<a href="https://colab.research.google.com/github/lisagamilton/python_tasks_logical/blob/main/pandas_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://drive.google.com/file/d/1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX/view?usp=sharing

https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists?resource=download

In [ ]:
! gdown --id 1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX
To: /content/HR_analytics.zip
100% 302k/302k [00:00<00:00, 28.3MB/s]

In [ ]:
! unzip /content/HR_analytics.zip

Archive:  /content/HR_analytics.zip
replace aug_test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [18]:
import pandas as pd
df = pd.read_csv('/content/aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# JOINS

In [ ]:
age = df[['enrollee_id']].copy()

In [ ]:
age['age'] = 30
age

       enrollee_id  age
0             8949   30
1            29725   30
2            11561   30
3            33241   30
4              666   30
...            ...  ...
19153         7386   30
19154        31398   30
19155        24576   30
19156         5756   30
19157        23834   30

[19158 rows x 2 columns]

In [ ]:
df = df.merge(age,how='left',on='enrollee_id')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target,age
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0,30
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0,30
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0,30
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0,30
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0,30
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0,30
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0,30
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0,30
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0,30

В результаті join можуть зявитися дублікати (однакові айді наприклад), тому варто перевіряти:

In [ ]:
len(df)

19158

No duplicates

In [ ]:
len(age['enrollee_id'].drop_duplicates())

19158

# loc, iloc

In [ ]:
#show only females with city and target as columns
df.loc[df['gender'] == 'Female',['city','target']]

           city  target
19      city_13     1.0
32     city_103     0.0
33     city_160     0.0
40     city_114     0.0
45      city_21     1.0
...         ...     ...
19056  city_103     0.0
19070  city_103     0.0
19110  city_103     0.0
19150  city_160     0.0
19152  city_103     0.0

[1238 rows x 2 columns]

In [ ]:
#Select people with training_hours > 100 and education_level = Masters, and display all columns.
df.loc[(df['training_hours'] > 100) & (df['education_level'] == 'Masters'),:]

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target,age
42,31654,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,50-99,Early Stage Startup,1,112,1.0,30
101,14672,city_173,0.878,NaN,No relevent experience,no_enrollment,Masters,STEM,>20,NaN,NaN,1,150,0.0,30
132,1924,city_102,0.804,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,100-500,Pvt Ltd,3,164,0.0,30
137,24829,city_103,0.920,Male,No relevent experience,no_enrollment,Masters,Humanities,3,10000+,Pvt Ltd,1,133,1.0,30
145,7777,city_114,0.926,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,NaN,NaN,never,120,0.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19040,6023,city_100,0.887,Male,Has relevent experience,no_enrollment,Masters,STEM,15,NaN,Pvt Ltd,>4,250,0.0,30
19049,12700,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,8,100-500,Pvt Ltd,1,143,0.0,30
19098,4390,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,10000+,Pvt Ltd,2,139,0.0,30
19114,12539,city_21,0.624,NaN,No relevent experience,no_enrollment,Masters,STEM,<1,<10,NaN,>4,160,1.0,30
19117,3458,city_114,0.926,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,NaN,NaN,>4,214,0.0,30

In [ ]:
#Modify: for all rows where training_hours > 100, set high_training = 1.
df.loc[df['training_hours'] > 100, 'high_training'] = 1
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target,age,high_training
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0,30,NaN
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0,30,NaN
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0,30,NaN
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0,30,NaN
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0,30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0,30,NaN
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0,30,NaN
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0,30,NaN
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0,30,NaN
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0,30,1.0

In [19]:
#Replace: all NaN values in gender with No_info
df['gender'] = df['gender'].fillna('No_info')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,No_info,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,No_info,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,No_info,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [21]:
#Select: the first 5 rows and all columns
df.iloc[:5,:]

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,No_info,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,No_info,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [26]:
#Select: the first 5 rows and only the first 3 columns
df.iloc[:5,:3]

   enrollee_id      city  city_development_index
0         8949  city_103                   0.920
1        29725   city_40                   0.776
2        11561   city_21                   0.624
3        33241  city_115                   0.789
4          666  city_162                   0.767

In [23]:
#Select: the 10th row and the 5th column
df.iloc[10,5]

'Full time course'

In [29]:
#last 3 rows
df.iloc[:,-3:]

      last_new_job  training_hours  target
0                1              36     1.0
1               >4              47     0.0
2            never              83     0.0
3            never              52     1.0
4                4               8     0.0
...            ...             ...     ...
19153            1              42     1.0
19154            4              52     1.0
19155            4              44     0.0
19156            2              97     0.0
19157            1             127     0.0

[19158 rows x 3 columns]