<a href="https://colab.research.google.com/github/lisagamilton/python_tasks_logical/blob/main/pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://drive.google.com/file/d/1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX/view?usp=sharing

https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists?resource=download

In [ ]:
! gdown --id 1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xbXbLi6CyIhmWTPj6_zYysNdKEsAcVLX
To: /content/HR_analytics.zip
100% 302k/302k [00:00<00:00, 27.6MB/s]

In [ ]:
! unzip /content/HR_analytics.zip

Archive:  /content/HR_analytics.zip
  inflating: aug_test.csv
  inflating: aug_train.csv
  inflating: sample_submission.csv

In [ ]:
import pandas as pd
df = pd.read_csv('/content/aug_train.csv')

# Pivot table

In [ ]:
def education_group(x):
  if x in ['High School','Primary School']:
    return 'School'
  if x in ['Masters','Phd']:
    return 'Masters and Phd'
  return x

In [ ]:
df['new_educational_level'] = df['education_level'].apply(education_group)

In [ ]:
df.groupby('new_educational_level')['target'].agg(['count','mean'])

                       count      mean
new_educational_level
Graduate               11598  0.279790
Masters and Phd         4775  0.207958
School                  2325  0.187097

In [ ]:
df.groupby('new_educational_level')['target'].agg(['count','mean'])

                       count      mean
new_educational_level
Graduate               11598  0.279790
Masters and Phd         4775  0.207958
School                  2325  0.187097

In [ ]:
df['new_educational_level'] = df['new_educational_level'].fillna('no_info')

In [ ]:
t = df.pivot_table(index='new_educational_level', values='target',aggfunc=['count','mean'])

In [ ]:
t.columns = ['_'.join(col).strip() for col in t.columns.values]
t

                       count_target  mean_target
new_educational_level
Graduate                      11598     0.279790
Masters and Phd                4775     0.207958
School                         2325     0.187097
no_info                         460     0.226087

In [ ]:
t.reset_index()

  new_educational_level  count_target  mean_target
0              Graduate         11598     0.279790
1       Masters and Phd          4775     0.207958
2                School          2325     0.187097
3               no_info           460     0.226087

Even though groupby is more comfortable in using in indexing, but pivot_table can add columns to the pivot!
It is useful when creating heatmaps

In [ ]:
df.pivot_table(index='new_educational_level',columns='gender', values='target',aggfunc=['count','mean'])

                       count                  mean
gender                Female  Male Other    Female      Male     Other
new_educational_level
Graduate                 773  8144   112  0.279431  0.257122  0.330357
Masters and Phd          386  3237    31  0.233161  0.186284  0.096774
School                    71  1598    39  0.267606  0.171464  0.205128
no_info                    8   242     9  0.125000  0.169421  0.222222