<a href="https://colab.research.google.com/github/lisagamilton/python_for_data_analysis/blob/main/pandas_db_connection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NULL VALUES

In [1]:
import pandas as pd
data = {
    'Name':['John Doe','Jane Smith','Bob Brown','Alice Johnson'],
    'Age':[28,34, None, 45],
    'Email':['john@example.com',None,'bob@example.com','alice@example.com']
}

df = pd.DataFrame(data)
df.isnull().sum()

Name     0
Age      1
Email    1
dtype: int64

In [2]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Email'] = df['Email'].fillna('unknown@example.com')
df

            Name        Age                Email
0       John Doe  28.000000     john@example.com
1     Jane Smith  34.000000  unknown@example.com
2      Bob Brown  35.666667      bob@example.com
3  Alice Johnson  45.000000    alice@example.com

In [3]:
#WRONG
data = {
    'Name':['John Doe','Jane Smith','Bob Brown','Alice Johnson'],
    'Age':[28,34, None, 45],
    'Email':['john@example.com',None,'bob@example.com','alice@example.com']
}

df = pd.DataFrame(data)
df = df['Email'].dropna()
print(type(df))

<class 'pandas.core.series.Series'>

In [4]:
#CORRECT
data = {
    'Name':['John Doe','Jane Smith','Bob Brown','Alice Johnson'],
    'Age':[28,34, None, 45],
    'Email':['john@example.com',None,'bob@example.com','alice@example.com']
}

df = pd.DataFrame(data)

df = df.dropna(subset = 'Email')
print(type(df))

<class 'pandas.core.frame.DataFrame'>

DUPLICATES

In [5]:
#method 1: checking if duplicates
#less convenient since you are checking each row yourself
data = {
    'Name':['John Doe','Jane Smith','John Doe','Alice Johnson'],
    'Age':[28,34,28,45],
    'Email':['john@example.com','jane@example.com','john@example.com','alice@example.com']
}

df = pd.DataFrame(data)
print(df.duplicated())

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
#method 2:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Email   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [7]:
#checking if there are duplicates with info and df_no_duplicates (without changing original data)
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

            Name  Age              Email
0       John Doe   28   john@example.com
1     Jane Smith   34   jane@example.com
3  Alice Johnson   45  alice@example.com

In [8]:
#checking duplicates regarding something: name, email, etc. (using 1st method)
data = {
    'Name':['John Doe','Jane Smith','John Doe','Alice Johnson'],
    'Age':[28,34,28,45],
    'Email':['john@example.com','jane@example.com','john@example.com','alice@example.com']
}

df = pd.DataFrame(data)
duplicates = df.duplicated(subset=['Name'])
print(duplicates)

df_no_duplicates = df.drop_duplicates(subset = 'Name')
print(df_no_duplicates)

0    False
1    False
2     True
3    False
dtype: bool
            Name  Age              Email
0       John Doe   28   john@example.com
1     Jane Smith   34   jane@example.com
3  Alice Johnson   45  alice@example.com

CONVERTING DATA TYPE

In [9]:
data = {
    'Name':['John Doe','Jane Smith','John Doe','Alice Johnson'],
    'Age':['28','34','28','45'], #age as string
    'JoinDate':['2022-01-15','2021-12-01','2022-03-22','2020-11-30'] #date as string
}

df = pd.DataFrame(data)
print(df.dtypes)

Name        object
Age         object
JoinDate    object
dtype: object

In [10]:
df['Age'] = df['Age'].astype('int')
df['JoinDate'] = pd.to_datetime(df['JoinDate'])
print(df.dtypes)
df

Name                object
Age                  int64
JoinDate    datetime64[ns]
dtype: object

            Name  Age   JoinDate
0       John Doe   28 2022-01-15
1     Jane Smith   34 2021-12-01
2       John Doe   28 2022-03-22
3  Alice Johnson   45 2020-11-30

In [11]:
#Date in another format
data = {
    'Name':['John Doe','Jane Smith','John Doe','Alice Johnson'],
    'Age':['28','34','28','45'], #age as string
    'JoinDate':['15-01-2022','01-12-2021','22-03-2022','30-11-2020'] #date as string
}

df = pd.DataFrame(data)
print(df.dtypes) #before
df['JoinDate'] = pd.to_datetime(df['JoinDate'],format='%d-%m-%Y') #формат даних яких ЗЧИТУЮТЬ. результат воно не поверне так, поверне в своєму стандартному форматі - рік, міс, день
print(df.dtypes) #after
df

Name        object
Age         object
JoinDate    object
dtype: object
Name                object
Age                 object
JoinDate    datetime64[ns]
dtype: object

            Name Age   JoinDate
0       John Doe  28 2022-01-15
1     Jane Smith  34 2021-12-01
2       John Doe  28 2022-03-22
3  Alice Johnson  45 2020-11-30

In [12]:
#if client wants a particulat format:
df['JoinDate'] = df['JoinDate'].dt.strftime('%d-%m-%Y')
df

            Name Age    JoinDate
0       John Doe  28  15-01-2022
1     Jane Smith  34  01-12-2021
2       John Doe  28  22-03-2022
3  Alice Johnson  45  30-11-2020

CLEANING DATA

In [13]:
import re

df = pd.DataFrame({
    'plan': [
        'Starter - 2022',
        'Pro - 2023',
        'Enterprise - 2023',
        'Starter',
        'Pro test account',
        None
    ],
    'revenue': [100, 200, 500, 120, 50, 300]
})

In [14]:
df['year_plan'] = df['plan'].str.extract(r'(\d{4})')
df

                plan  revenue year_plan
0     Starter - 2022      100      2022
1         Pro - 2023      200      2023
2  Enterprise - 2023      500      2023
3            Starter      120       NaN
4   Pro test account       50       NaN
5               None      300       NaN

In [15]:
df['plan_clean'] = df['plan'].str.replace(r'\d+|-', '', regex=True).str.strip()
df

                plan  revenue year_plan        plan_clean
0     Starter - 2022      100      2022           Starter
1         Pro - 2023      200      2023               Pro
2  Enterprise - 2023      500      2023        Enterprise
3            Starter      120       NaN           Starter
4   Pro test account       50       NaN  Pro test account
5               None      300       NaN              None

In [16]:
#Створи колонку segment: Starter → "Small"; Pro → "Medium"; Enterprise → "Big"; test account → "Test"; None → "Unknown"

mapping = {
    'Starter':'Small',
    'Pro':'Medium',
    'Enterprise':'Big',
    'test account':'Test'
}

df['segment'] = df['plan_clean'].map(mapping)
df['segment'] = df['segment'].fillna('Unknown')
df

                plan  revenue year_plan        plan_clean  segment
0     Starter - 2022      100      2022           Starter    Small
1         Pro - 2023      200      2023               Pro   Medium
2  Enterprise - 2023      500      2023        Enterprise      Big
3            Starter      120       NaN           Starter    Small
4   Pro test account       50       NaN  Pro test account  Unknown
5               None      300       NaN              None  Unknown

# Task: Subscription Revenue Analysis
- Group data by year and plan, calculate total revenue
- Create a new column:
Small team → Starter, Squad
Big team → all other plans

In [17]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd

In [18]:
credentials = service_account.Credentials.from_service_account_file('/content/credentials.json')
project_id = 'my-project-26-01-2026'
client = bigquery.Client(credentials = credentials, project=project_id)
query_text = f"""SELECT * FROM `my-project-26-01-2026.dataset1.subscriptions`;"""
query = client.query(query_text)
subscriptions = query.to_dataframe()
subscriptions

,customer_id,subscriprion_id,start_date,month,amount,plan
0,1255,173645579,2023-06-12,<NA>,<NA>,Squad
1,1298,173645682,2023-10-13,1,968,Squad
2,1255,173645579,2023-06-12,1,60,Squad
3,1284,173645668,2023-09-29,2,697,Squad
4,1288,173645612,2023-08-04,3,978,Squad
...,...,...,...,...,...,...
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023
310,1286,173645490,2022-09-15,6,536,Squad test account
311,1269,173645593,2023-07-16,12,223,Squad test account
312,1290,173645494,2022-10-19,1,878,Starter test account
313,1242,173645566,2023-05-30,2,526,Business test account

In [19]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      314 non-null    Int64
 1   subscriprion_id  314 non-null    Int64
 2   start_date       314 non-null    dbdate
 3   month            311 non-null    Int64
 4   amount           311 non-null    Int64
 5   plan             314 non-null    object
dtypes: Int64(4), dbdate(1), object(1)
memory usage: 16.1+ KB

In [20]:
#in this case it is better to delete duplicates (after asking the team/business decision maker)
subscriptions = subscriptions.drop_duplicates()
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      314 non-null    Int64
 1   subscriprion_id  314 non-null    Int64
 2   start_date       314 non-null    dbdate
 3   month            311 non-null    Int64
 4   amount           311 non-null    Int64
 5   plan             314 non-null    object
dtypes: Int64(4), dbdate(1), object(1)
memory usage: 16.1+ KB

In [21]:
#It’s better to convert IDs to strings because they are identifiers, not values for calculation,
#and keeping them as strings preserves formatting and prevents data mismatches.
subscriptions['customer_id'] = subscriptions['customer_id'].astype('str')
subscriptions['subscriprion_id'] = subscriptions['subscriprion_id'].astype('str')

In [22]:
##in this case it is better to delete Null values (after asking the team/business decision maker)
subscriptions = subscriptions.dropna()
subscriptions.describe()

          month      amount
count     311.0       311.0
mean   6.684887  494.231511
std    3.297662   286.68151
min         1.0         5.0
25%         4.0       258.5
50%         7.0       491.0
75%        10.0       732.5
max        12.0       995.0

In [23]:
subscriptions = subscriptions.dropna()
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 1 to 313
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      311 non-null    object
 1   subscriprion_id  311 non-null    object
 2   start_date       311 non-null    dbdate
 3   month            311 non-null    Int64
 4   amount           311 non-null    Int64
 5   plan             311 non-null    object
dtypes: Int64(2), dbdate(1), object(3)
memory usage: 17.6+ KB

In [24]:
print(subscriptions['plan'].unique())

['Squad' 'Starter' 'Business' 'Starter +' 'Enterprise' 'Business +++'
 'Squad - 2022' 'Squad - 2023' 'Starter - 2022' 'Starter - 2023'
 'Business - 2022' 'Business - 2023' 'Enterprise - 2022'
 'Enterprise - 2023' 'Squad test account' 'Starter test account'
 'Business test account']

In [25]:
import re
text = 'Starter - 2022'
year = re.search(r'\d+',text).group()
print(year)

2022

In [26]:
subscriptions['plan_year'] = subscriptions['plan'].apply(lambda x: re.sub(r"[^0-9]+","",x))
subscriptions

,customer_id,subscriprion_id,start_date,month,amount,plan,plan_year
1,1298,173645682,2023-10-13,1,968,Squad,
2,1255,173645579,2023-06-12,1,60,Squad,
3,1284,173645668,2023-09-29,2,697,Squad,
4,1288,173645612,2023-08-04,3,978,Squad,
5,1298,173645682,2023-10-13,3,832,Squad,
...,...,...,...,...,...,...,...
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023,2023
310,1286,173645490,2022-09-15,6,536,Squad test account,
311,1269,173645593,2023-07-16,12,223,Squad test account,
312,1290,173645494,2022-10-19,1,878,Starter test account,
313,1242,173645566,2023-05-30,2,526,Business test account,

In [27]:
#Filtering out 'test' subscriptions
# ~ is 'NOT' operator - making everything opposite
subscriptions = subscriptions.loc[~subscriptions['plan'].str.contains('test')]
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 307 entries, 1 to 309
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      307 non-null    object
 1   subscriprion_id  307 non-null    object
 2   start_date       307 non-null    dbdate
 3   month            307 non-null    Int64
 4   amount           307 non-null    Int64
 5   plan             307 non-null    object
 6   plan_year        307 non-null    object
dtypes: Int64(2), dbdate(1), object(4)
memory usage: 19.8+ KB

In [28]:
#we can change the empty rows like this
new_subscriptions = subscriptions.loc[subscriptions['plan_year'].str.contains(r'\d')]
new_subscriptions

,customer_id,subscriprion_id,start_date,month,amount,plan,plan_year
182,1286,173645430,2022-02-04,2,332,Squad - 2022,2022
183,1280,173645424,2022-01-22,3,195,Squad - 2022,2022
184,1250,173645454,2022-07-20,3,460,Squad - 2022,2022
185,1274,173645418,2022-01-16,4,989,Squad - 2022,2022
186,1262,173645406,2022-01-04,5,321,Squad - 2022,2022
...,...,...,...,...,...,...,...
305,1273,173645477,2022-09-02,3,611,Enterprise - 2023,2023
306,1263,173645467,2022-07-23,6,440,Enterprise - 2023,2023
307,1278,173645482,2022-09-07,8,553,Enterprise - 2023,2023
308,1283,173645487,2022-09-12,9,745,Enterprise - 2023,2023
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023,2023

In [29]:
#or like this
subscriptions.loc[subscriptions['plan_year'] == "", 'plan_year'] = 2021
subscriptions

,customer_id,subscriprion_id,start_date,month,amount,plan,plan_year
1,1298,173645682,2023-10-13,1,968,Squad,2021
2,1255,173645579,2023-06-12,1,60,Squad,2021
3,1284,173645668,2023-09-29,2,697,Squad,2021
4,1288,173645612,2023-08-04,3,978,Squad,2021
5,1298,173645682,2023-10-13,3,832,Squad,2021
...,...,...,...,...,...,...,...
305,1273,173645477,2022-09-02,3,611,Enterprise - 2023,2023
306,1263,173645467,2022-07-23,6,440,Enterprise - 2023,2023
307,1278,173645482,2022-09-07,8,553,Enterprise - 2023,2023
308,1283,173645487,2022-09-12,9,745,Enterprise - 2023,2023
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023,2023

In [30]:
subscriptions['plan_cleaned'] = subscriptions['plan'].str.extract(r'([A-Za-z]*)')
subscriptions

/tmp/ipykernel_16875/918049574.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subscriptions['plan_cleaned'] = subscriptions['plan'].str.extract(r'([A-Za-z]*)')

,customer_id,subscriprion_id,start_date,month,amount,plan,plan_year,plan_cleaned
1,1298,173645682,2023-10-13,1,968,Squad,2021,Squad
2,1255,173645579,2023-06-12,1,60,Squad,2021,Squad
3,1284,173645668,2023-09-29,2,697,Squad,2021,Squad
4,1288,173645612,2023-08-04,3,978,Squad,2021,Squad
5,1298,173645682,2023-10-13,3,832,Squad,2021,Squad
...,...,...,...,...,...,...,...,...
305,1273,173645477,2022-09-02,3,611,Enterprise - 2023,2023,Enterprise
306,1263,173645467,2022-07-23,6,440,Enterprise - 2023,2023,Enterprise
307,1278,173645482,2022-09-07,8,553,Enterprise - 2023,2023,Enterprise
308,1283,173645487,2022-09-12,9,745,Enterprise - 2023,2023,Enterprise
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023,2023,Enterprise

In [31]:
#Creating new column 'plan_group', assigning 'Small team' or 'Big team'
for index, row in subscriptions.iterrows():
    if row['plan_cleaned'] in ('Starter', 'Squad'):
        subscriptions.loc[index, 'plan_group'] = 'Small team'
    else:
        subscriptions.loc[index, 'plan_group'] = 'Big team'
subscriptions

/tmp/ipykernel_16875/1304726344.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subscriptions.loc[index, 'plan_group'] = 'Small team'

,customer_id,subscriprion_id,start_date,month,amount,plan,plan_year,plan_cleaned,plan_group
1,1298,173645682,2023-10-13,1,968,Squad,2021,Squad,Small team
2,1255,173645579,2023-06-12,1,60,Squad,2021,Squad,Small team
3,1284,173645668,2023-09-29,2,697,Squad,2021,Squad,Small team
4,1288,173645612,2023-08-04,3,978,Squad,2021,Squad,Small team
5,1298,173645682,2023-10-13,3,832,Squad,2021,Squad,Small team
...,...,...,...,...,...,...,...,...,...
305,1273,173645477,2022-09-02,3,611,Enterprise - 2023,2023,Enterprise,Big team
306,1263,173645467,2022-07-23,6,440,Enterprise - 2023,2023,Enterprise,Big team
307,1278,173645482,2022-09-07,8,553,Enterprise - 2023,2023,Enterprise,Big team
308,1283,173645487,2022-09-12,9,745,Enterprise - 2023,2023,Enterprise,Big team
309,1268,173645472,2022-08-28,10,37,Enterprise - 2023,2023,Enterprise,Big team

In [32]:
sales_by_plan = subscriptions.groupby('plan_cleaned')['amount'].sum()
sales_by_plan

plan_cleaned
Business      28207
Enterprise    28548
Squad         34495
Starter       60293
Name: amount, dtype: Int64

In [33]:
data = [
    [1001, 50001, "2023-01-10", "1", 29, "Starter 2023", "EU", "web", "active"],
    [1002, 50002, "2023-02-15", "2", 59, "Pro 2023", "EU", "mobile", "active"],
    [1003, 50003, "2023-03-20", None, None, "Enterprise test", "US", "desktop", "test"],
    [1004, 50004, "2023-01-25", "1", 99, "Squad 2022", "EU", "web", "canceled"],
    [1005, 50005, "2023-04-05", "4", 49, "Starter 2024", "ASIA", "mobile", "active"],
    [1006, 50006, "2023-05-11", "5", 199, "Enterprise 2024", "US", "web", "active"],
    [1007, 50007, "2023-06-17", "6", 59, "Pro test account", "EU", "desktop", "test"],
    [1008, 50008, "2023-07-21", "7", 29, "Starter 2023", "ASIA", "mobile", "active"],
    [1009, 50009, "2023-08-30", "8", None, "Squad 2023", "EU", "web", "paused"],
    [1010, 50010, "2023-09-12", "9", 199, "Enterprise 2023", "US", "desktop", "active"],
    [1011, 50011, "2023-10-01", "10", 59, "Pro 2024", "EU", "mobile", "canceled"],
    [1012, 50012, "2023-11-18", "11", 29, "Starter test", "ASIA", "web", "test"],
    [1013, 50013, "2023-12-25", "12", 99, "Squad 2024", "EU", "mobile", "active"],
    [1014, 50014, "2023-01-05", "1", 199, "Enterprise 2023", "US", "web", "active"],
    [1015, 50015, "2023-02-14", "2", 49, "Starter 2023", "EU", "desktop", "active"],
]

columns = [
    "user_id",
    "subscription_id",
    "signup_date",
    "billing_month",
    "revenue",
    "plan",
    "region",
    "device",
    "status"
]

df = pd.DataFrame(data, columns=columns)
df

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active
2,1003,50003,2023-03-20,None,NaN,Enterprise test,US,desktop,test
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active
6,1007,50007,2023-06-17,6,59.0,Pro test account,EU,desktop,test
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active
8,1009,50009,2023-08-30,8,NaN,Squad 2023,EU,web,paused
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled
11,1012,50012,2023-11-18,11,29.0,Starter test,ASIA,web,test
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active

In [34]:
#insights: 1) cleaning duplicates as it's said to be a mistake 2) if null values in revenue - delete them, same for user_id, sub_id, plan
#3)changing data type of id, signup_date
#4) grouping data into months (no change in dataset) 5) creating groups for plan - small team and big team 6) plan_year and plan_clean

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          15 non-null     int64
 1   subscription_id  15 non-null     int64
 2   signup_date      15 non-null     object
 3   billing_month    14 non-null     object
 4   revenue          13 non-null     float64
 5   plan             15 non-null     object
 6   region           15 non-null     object
 7   device           15 non-null     object
 8   status           15 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 1.2+ KB

In [36]:
#i would delete the duplicated rows where all the columns are identical
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates.info())
df_no_duplicates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          15 non-null     int64
 1   subscription_id  15 non-null     int64
 2   signup_date      15 non-null     object
 3   billing_month    14 non-null     object
 4   revenue          13 non-null     float64
 5   plan             15 non-null     object
 6   region           15 non-null     object
 7   device           15 non-null     object
 8   status           15 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 1.2+ KB
None

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active
2,1003,50003,2023-03-20,None,NaN,Enterprise test,US,desktop,test
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active
6,1007,50007,2023-06-17,6,59.0,Pro test account,EU,desktop,test
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active
8,1009,50009,2023-08-30,8,NaN,Squad 2023,EU,web,paused
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled
11,1012,50012,2023-11-18,11,29.0,Starter test,ASIA,web,test
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active

In [37]:
df = df.dropna(subset = ['user_id','subscription_id','revenue','plan'])
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 14
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          13 non-null     int64
 1   subscription_id  13 non-null     int64
 2   signup_date      13 non-null     object
 3   billing_month    13 non-null     object
 4   revenue          13 non-null     float64
 5   plan             13 non-null     object
 6   region           13 non-null     object
 7   device           13 non-null     object
 8   status           13 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 1.0+ KB
None

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active
6,1007,50007,2023-06-17,6,59.0,Pro test account,EU,desktop,test
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled
11,1012,50012,2023-11-18,11,29.0,Starter test,ASIA,web,test
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active

In [38]:
#Converting to correct data type
df['user_id'] = df['user_id'].astype('str')
df['subscription_id'] = df['subscription_id'].astype('str')
df['signup_date'] = pd.to_datetime(df['signup_date'])
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 14
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          13 non-null     object
 1   subscription_id  13 non-null     object
 2   signup_date      13 non-null     datetime64[ns]
 3   billing_month    13 non-null     object
 4   revenue          13 non-null     float64
 5   plan             13 non-null     object
 6   region           13 non-null     object
 7   device           13 non-null     object
 8   status           13 non-null     object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 1.6+ KB
None

/tmp/ipykernel_16875/3554450748.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_id'] = df['user_id'].astype('str')
/tmp/ipykernel_16875/3554450748.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['subscription_id'] = df['subscription_id'].astype('str')
/tmp/ipykernel_16875/3554450748.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signup_date'] = pd.to_datetime(df['signup_date'])

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active
6,1007,50007,2023-06-17,6,59.0,Pro test account,EU,desktop,test
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled
11,1012,50012,2023-11-18,11,29.0,Starter test,ASIA,web,test
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active

In [39]:
df['plan_clean'] = df['plan'].str.extract(r'([A-Za-z]+)')
df['year_plan'] = df['plan'].str.extract(r'(\d+)')
df

/tmp/ipykernel_16875/463410706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plan_clean'] = df['plan'].str.extract(r'([A-Za-z]+)')
/tmp/ipykernel_16875/463410706.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year_plan'] = df['plan'].str.extract(r'(\d+)')

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status,plan_clean,year_plan
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active,Starter,2023
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active,Pro,2023
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled,Squad,2022
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active,Starter,2024
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active,Enterprise,2024
6,1007,50007,2023-06-17,6,59.0,Pro test account,EU,desktop,test,Pro,NaN
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active,Starter,2023
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active,Enterprise,2023
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled,Pro,2024
11,1012,50012,2023-11-18,11,29.0,Starter test,ASIA,web,test,Starter,NaN
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active,Squad,2024
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active,Enterprise,2023
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active,Starter,2023

In [40]:
df = df.loc[~df['plan'].str.contains('test',na=False)]
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 14
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          11 non-null     object
 1   subscription_id  11 non-null     object
 2   signup_date      11 non-null     datetime64[ns]
 3   billing_month    11 non-null     object
 4   revenue          11 non-null     float64
 5   plan             11 non-null     object
 6   region           11 non-null     object
 7   device           11 non-null     object
 8   status           11 non-null     object
 9   plan_clean       11 non-null     object
 10  year_plan        11 non-null     object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 1.0+ KB
None

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status,plan_clean,year_plan
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active,Starter,2023
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active,Pro,2023
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled,Squad,2022
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active,Starter,2024
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active,Enterprise,2024
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active,Starter,2023
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active,Enterprise,2023
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled,Pro,2024
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active,Squad,2024
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active,Enterprise,2023
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active,Starter,2023

In [41]:
#revenue analysis
df['revenue_per_user'] = df.groupby('user_id')['revenue'].transform('sum')
df

/tmp/ipykernel_16875/338179273.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue_per_user'] = df.groupby('user_id')['revenue'].transform('sum')

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status,plan_clean,year_plan,revenue_per_user
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active,Starter,2023,29.0
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active,Pro,2023,59.0
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled,Squad,2022,99.0
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active,Starter,2024,49.0
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active,Enterprise,2024,199.0
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active,Starter,2023,29.0
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active,Enterprise,2023,199.0
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled,Pro,2024,59.0
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active,Squad,2024,99.0
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active,Enterprise,2023,199.0
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active,Starter,2023,49.0

In [42]:
df['plan_group'] = df['plan_clean'].apply(lambda x: 'Small team' if x in ('Starter','Squad') else 'Big team')
df

/tmp/ipykernel_16875/3782537493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plan_group'] = df['plan_clean'].apply(lambda x: 'Small team' if x in ('Starter','Squad') else 'Big team')

,user_id,subscription_id,signup_date,billing_month,revenue,plan,region,device,status,plan_clean,year_plan,revenue_per_user,plan_group
0,1001,50001,2023-01-10,1,29.0,Starter 2023,EU,web,active,Starter,2023,29.0,Small team
1,1002,50002,2023-02-15,2,59.0,Pro 2023,EU,mobile,active,Pro,2023,59.0,Big team
3,1004,50004,2023-01-25,1,99.0,Squad 2022,EU,web,canceled,Squad,2022,99.0,Small team
4,1005,50005,2023-04-05,4,49.0,Starter 2024,ASIA,mobile,active,Starter,2024,49.0,Small team
5,1006,50006,2023-05-11,5,199.0,Enterprise 2024,US,web,active,Enterprise,2024,199.0,Big team
7,1008,50008,2023-07-21,7,29.0,Starter 2023,ASIA,mobile,active,Starter,2023,29.0,Small team
9,1010,50010,2023-09-12,9,199.0,Enterprise 2023,US,desktop,active,Enterprise,2023,199.0,Big team
10,1011,50011,2023-10-01,10,59.0,Pro 2024,EU,mobile,canceled,Pro,2024,59.0,Big team
12,1013,50013,2023-12-25,12,99.0,Squad 2024,EU,mobile,active,Squad,2024,99.0,Small team
13,1014,50014,2023-01-05,1,199.0,Enterprise 2023,US,web,active,Enterprise,2023,199.0,Big team
14,1015,50015,2023-02-14,2,49.0,Starter 2023,EU,desktop,active,Starter,2023,49.0,Small team

In [43]:
#What plan brings the most revenue?
df.groupby('plan_clean')['revenue'].sum().sort_values(ascending = False)

plan_clean
Enterprise    597.0
Squad         198.0
Starter       156.0
Pro           118.0
Name: revenue, dtype: float64

In [45]:
#What is the (overall) churn rate?
canceled_users = len(df.loc[df['status'] == 'canceled'])
churn_rate = canceled_users/len(df)
print(f'Churn rate for the company is: {churn_rate:.2%}')

Churn rate for the company is: 18.18%

In [46]:
#What is the (monthly) churn rate?
df['month'] = df['signup_date'].dt.to_period('M')
churn_rate = df.groupby('month')['status'].apply(lambda x: (x == 'canceled').sum()/len(x))
churn_rate

/tmp/ipykernel_16875/2842419421.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['signup_date'].dt.to_period('M')

month
2023-01    0.333333
2023-02    0.000000
2023-04    0.000000
2023-05    0.000000
2023-07    0.000000
2023-09    0.000000
2023-10    1.000000
2023-12    0.000000
Freq: M, Name: status, dtype: float64

In [47]:
#What is the churn rate regarding plan?
plan_churn_rate = df.groupby('plan_clean')['status'].apply(lambda x: (x == 'canceled').sum()/len(x))
plan_churn_rate

plan_clean
Enterprise    0.0
Pro           0.5
Squad         0.5
Starter       0.0
Name: status, dtype: float64

In [48]:
#Який регіон найбільш активний?
df[df['status'] == 'active'].groupby('region').size().sort_values(ascending=False)

region
EU      4
US      3
ASIA    2
dtype: int64

In [49]:
result = df.groupby('region').agg(total_users = ('status','size'),
                                  active_users_rate = ('status',lambda x:
                                  (x == 'active').mean()))
result

        total_users  active_users_rate
region
ASIA              2           1.000000
EU                6           0.666667
US                3           1.000000